### PR TITLE
fix #1016 - lion head displayed behind stats on landscape

### LINKED ISSUE #1016: Lion head is not shown when orientation changes for private tabs
- Did you search for similar issues before submitting this one?
Yes

- Description:
Lion head is not shown when orientation changes for private tabs

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6(iOS 10.3.2)

- Brave Version:
1.4 (17.07.31.11)

- Steps to reproduce:
    1. Open a Private tab and visit a site
    2. Change orientation to landscape and close the tab
    3. Lion head is shown in between Tracker count and HTTPS count
    4. Open a new tab in landscape mode, doesn't show the Lion head in between the badge

- Actual Behavior
Lion head is not shown when orientation changes for private tabs

- Expected Behavior
Should either show/not show the lion head when orientation changes

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by jamesmudgett**
(private browsing mode)

### CODE REVIEW

File: Client/Frontend/Home/TopSitesPanel.swift [hunk 1]
```diff
@@ -191,6 +191,12 @@ class TopSitesPanel: UIViewController {
             make.right.equalTo(0)
             make.bottom.equalTo(0)
         }
+        
+        let toInterfaceOrientation = UIApplication.shared.statusBarOrientation
```
Comment (jhreis) [inline Client/Frontend/Home/TopSitesPanel.swift]: Instead of duplicating this logic from `handleRotation` can we just call `handleRotation` here?

File: Client/Frontend/Home/TopSitesPanel.swift [hunk 2]
```diff
@@ -191,6 +191,12 @@ class TopSitesPanel: UIViewController {
...
+        if (toInterfaceOrientation == .landscapeLeft || toInterfaceOrientation == .landscapeRight) &&
```
Comment (jhreis) [inline Client/Frontend/Home/TopSitesPanel.swift]: Can just use `toInterfaceOrientation.isLandscape` which checks against both.

Comment (jamesmudgett) [inline Client/Frontend/Home/TopSitesPanel.swift]: Good call

File: Client/Frontend/Home/TopSitesPanel.swift (hunk 1 above)
Comment (jamesmudgett) [inline Client/Frontend/Home/TopSitesPanel.swift]: good call
