### PR TITLE
fix #1013 - crash between closing private tab and restoring normal tabs

### LINKED ISSUE #1013: Browser crashes when exiting Private browsing
- Did you search for similar issues before submitting this one?
Yes

- Description:
Browser crashes when exiting Private browsing

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+(10.3.3)

- Brave Version:
1.4(17.07.31.11)

- Steps to reproduce:
    1. Clean install beta build
    2. Open a new tab, load a site
    3. Tap on tab container, tap on private, open a new private tab
    4. Tap on left menu, go to settings
    5. Tap on done to go back to private tab, tap on tab container, tap on private to exit private mode, browser crashes

- Actual Behavior
Browser crashes when exiting Private mode

- Expected Behavior
Should not crash

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Above steps doesn't crash the stable build as mentioned on #880 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Open few normal tabs
    2. Open a new private tab and load a page
    3. Tap on the notification for other apps, so that it switches to different app (and shows back to brave on top left)
    4. Navigate back to Brave and close private tab, browser crashes

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed: 

- Any related issues:

### PR DESCRIPTION
**Pull request by jamesmudgett**

### CODE REVIEW

File: Client/Frontend/Browser/Browser.swift [hunk 1]
```diff
@@ -310,8 +310,8 @@ class Browser: NSObject, BrowserWebViewDelegate {
                 // Freshly created web views won't have any history entries at all.
                 // If we have no history, abort.
                 if currentItem != nil {
-                    let backList = wv.backForwardList.backList ?? []
-                    let forwardList = wv.backForwardList.forwardList ?? []
+                    let backList = wv.backForwardList.backList
```
Comment (jamesmudgett) [inline Client/Frontend/Browser/Browser.swift]: These were just cleanup

File: Client/Frontend/Browser/SessionData.swift [hunk 2]
```diff
@@ -26,7 +26,7 @@ class SessionData: NSObject, NSCoding {
     var savedTabData: SavedTab {
         // (id: String, title: String, url: String, isSelected: Bool, order: Int16, screenshot: UIImage?, history: [String], historyIndex: Int16)
         let urlStrings = urls.map { $0.absoluteString }
-        let currentURL = urlStrings[currentPage] ?? ""
+        let currentURL = urlStrings[(currentPage < 0 ? 0 : currentPage)]
```
Comment (jhreis) [inline Client/Frontend/Browser/SessionData.swift]: Can do: `urlStrings[max(currentPage, 0)]` which forces the 'index' to be at least 0.

Comment (jamesmudgett) [inline Client/Frontend/Browser/SessionData.swift]: Had some variation of this originally then got lost in trying to make it default to end of urls list, then fell back to original. I agree, also would it make sense to default to urlStrings.count-1 instead of 0 in the history stack?

Comment (jhreis) [inline Client/Frontend/Browser/SessionData.swift]: Yeah, I think probably so. If a tab has been persistent for a long time, the first history item, could be super random to the user. I think it would probably be better. In that case you could just retain the current logic (as the whole `min`/`max` thing won't really work).

Comment (jamesmudgett) [inline Client/Frontend/Browser/SessionData.swift]: could do...

// as current page could be negative but we want to possibly observe it's value if > 0
> max(max(currentPage, 0), min(currentPage, urlStrings.count-1))

thoughts?
