### PR TITLE
Fix #1420, fix #1010, fix #750, fix #850, fix #1285 url/address bar improvements.

### LINKED ISSUE #750: SwiftKeys keyboard keeping first letter when using predictive text
Description:

The SwiftKey keyboard has full access. After I type a few characters into the empty URL bar and then select a word suggested by SwiftKey the first letter remains in the URL.

For example if I type in "publi" into the empty URL bar, SwiftKey will suggest "public". When l select the suggestion "ppublic" is put in the URL bar instead of "public". I this only occurs for the first word in the URL.

https://community.brave.com/t/first-character-is-left-in-url-when-using-swiftkey-prediction/1688

**Did you search for similar issues before submitting this one?**

**Expected behavior:**

- Device (iPhone5, iPhone6s plus, iPad 3, ?):

- Brave Version:

- Steps to reproduce:
    1. Install SwiftKeys
    2. Open Brave
    3. Select URL Bar
    4. Type "T"
    5. Select recommended word (e.g. "The")
    6. The URL will now show "TThe" instead of just "The"

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #850: URL bar does not accept any character after the first from Swype keyboard when typing
Description: When using the Swype keyboard to type individual characters in the URL bar, the second character of your URL is not displayed (neither are subsequent characters like the 3rd, 4th, etc). Note, you must be typing the characters individually, not using the swipe feature of the keyboard. 

Workaround: If you switch to the standard Apple keyboard without the swype functionality, this is not a problem.

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
URL should be able to be typed out using the Swype keyboard just as if you were using the standard Apple keyboard.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS version 10.2.1)

- Brave Version:
1.3.1

- Steps to reproduce:
Pre-condition: Swype keyboard is installed on the iPhone.

1. Tap the URL bar, verify Swype is the keyboard being used, and begin to type something such as nytimes.com. (the URL bar suggests this site)
2. Navigate to the site and add it as a Bookmark.
3. Tap on the URL bar again.
4. This time, type something like 'philadelphia'.
5. You will see that 'pinterest.com' is pre-populated, but the 2nd, 3rd, etc characters you typed were not picked up in the URL bar.
6. Clear out pinterest.com and try something else like 'git', you will see the same results.

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

- Any related issues:
#750

### LINKED ISSUE #1010: Weird keyboard effect when opening a site when set to third party keyboard
- Did you search for similar issues before submitting this one?
Yes

- Description:
Weird keyboard effect when opening a site 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+(iOS 10.3.3), iPhone 6 (iOS 10.3.2)

- Brave Version:
1.4(17.07.31.11)

- Steps to reproduce:
    1. Change device language to any other than English (thirdparty keyboard)
    2. Clean install Brave beta 1.4, 
    3. Open a tab, make sure the keyboard is shown, switch to the thirdparty keyboard)
    4. Type a site name/tap on the top site tiles, before page loads keyboard goes white and then hides

- Actual Behavior
See attached video 

- Expected Behavior
Should not have this effect

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
[keyboard.zip](https://github.com/brave/browser-ios/files/1188558/keyboard.zip)

- Any related issues:

### LINKED ISSUE #1285: Autocomplete suggestions cannot be removed with backspace
### Description:
Autocomplete suggestions cannot be removed with backspace

### Steps to Reproduce
  1. Install 1.5 
  2. Type git in a new tab
  3. Ensure auto complete shows github.com with hub.com auto compelted
  4. Tap  on the auto complete text, only git part is selected
  5. Tap on backspace, doesn't delete the auto selected text 

**Actual result:**
image

**Expected result:**
Should be able to delete with backspace

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version:
1.5 (17.10.30.12)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad (iOS 11), iPhone 7+ (iOS 10)

### Is this an issue in the currently released version?
Yes

### LINKED ISSUE #1420: Tap after autocomplete suggestion does not remove selection
### Description:

When omnibar displays an autocomplete suggestion (say: `reddit.com/`) the not-yet-typed part of the address is selected. Other browsers (including Firefox Focus) allow user to remove the selection and continue typing by tapping the address bar. However, the same action in Brave iOS does nothing.

My use case is rather simple, I'd like to type `re` to get `reddit.com/` suggestion, then deselect it and type `r/funny` or `r/gifs`, etc.

### Steps to Reproduce

  1. Type `re` in omnibar to get `reddit.com/` suggestion
  2. Tap suggestion, or after it
  3. Observe that selected text in omnibar

**Actual result:**

Selected text stays selected

**Expected result:**

Selection should disappear, and user should be left with suggestion and blinking cursor after it.

**Reproduces how often:** [Easily reproduced/Intermittent issue]

Always/Easily reproduced

**Brave Version:**

v1.5.2 (17.12.12.15)

**Device details:**

iPad Pro 12.9'' (iOS 11.2.5)

**Website problems only:**
- [x] did you check with Brave Shields down?

- [x] did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- [x] did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
Mainly changes from upstream.
This PR fixes most problems with url/address bar, copying, navigating around autocompletion text field.
Also support for 3rd party keyboards should improve.

Swype keyboard isn't available in Polish app store, please test it if you are able to install it.

### CODE REVIEW

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 1]
```diff
@@ -69,17 +72,69 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
+        super.addTarget(self, action: #selector(AutocompleteTextField.textDidChange(_:)), for: UIControlEvents.editingChanged)
         notifyTextChanged = debounce(0.1, action: {
             if self.isEditing {
-                self.autocompleteDelegate?.autocompleteTextField(self, didEnterText: self.enteredText.stringByTrimmingLeadingCharactersInSet(NSCharacterSet.whitespaces))
+                self.autocompleteDelegate?.autocompleteTextField(self, didEnterText: self.normalizeString(self.text ?? ""))
             }
         })
     }
 
+    override var keyCommands: [UIKeyCommand]? {
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: Are these entirely new commands you added?

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 2]
```diff
@@ -69,17 +72,69 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
+                    return
+                }
+
+                guard let cursorPosition = position(from: range.start, offset: -1) else {
+                    return
+                }
+
+                selectedTextRange = textRange(from: cursorPosition, to: cursorPosition)
+            }
+            return
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: Not needed in a `switch`

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 3]
```diff
@@ -69,17 +72,69 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
+    }
+
+    func handleKeyCommand(sender: UIKeyCommand) {
+        switch sender.input {
+        case UIKeyInputLeftArrow:
+            if isSelectionActive {
+                applyCompletion()
+
+                // Set the current position to the beginning of the text.
+                selectedTextRange = textRange(from: beginningOfDocument, to: beginningOfDocument)
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: Setup a function variable, since the `textRange` selection is all identical, just have a variable to store `beginningOfDocument` / `cursorPosition` / etc...

Then set `selectedTextRange` after the `switch`

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 4]
```diff
@@ -69,17 +72,69 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
+        }
+    }
+
     func highlightAll() {
-        // Old behavior was to create a highlight on all text, then set from: to: to beginning of document to create a selection without cursor indicators. This caused two problems. 1. the indicators to allow selection were missing and required additional taps to select substring. 2. force touch on iPhone 6s and greater was not working and would create a two pixel cursor due to hacky set.
-        selectedTextRange = textRange(from: beginningOfDocument, to: endOfDocument)
+        let text = self.text
+        self.text = ""
+        setAutocompleteSuggestion(text ?? "")
+        selectedTextRange = textRange(from: endOfDocument, to: endOfDocument)
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: I think this should be beginningOfDocument..endOfDocument, instead of end..end

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 5]
```diff
@@ -88,83 +143,74 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
-            // cached query will get updated.
-            notifyTextChanged?()
-        }
+        // Clear the current completion, then set the text without the attributed style.
+        let text = (self.text ?? "") + (self.autocompleteTextLabel?.text ?? "")
+        removeCompletion()
+        self.text = text
+        hideCursor = false
+        // Move the cursor to the end of the completion.
+        selectedTextRange = textRange(from: endOfDocument, to: endOfDocument)
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: I think since this is so common x..x, you should probably create a helper for it, `textRange(at: foo)`

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 6]
```diff
@@ -88,83 +143,74 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
-            if suggestion.startsWith(normalizeString(enteredText)) && normalizeString(enteredText).characters.count < suggestion.characters.count {
-                let endingString = suggestion.substring(from: suggestion.characters.index(suggestion.startIndex, offsetBy: normalizeString(enteredText).characters.count))
-                let completedAndMarkedString = NSMutableAttributedString(string: enteredText + endingString)
-                completedAndMarkedString.addAttribute(NSBackgroundColorAttributeName, value: highlightColor, range: NSMakeRange(enteredText.characters.count, endingString.characters.count))
-                attributedText = completedAndMarkedString
-                completionActive = true
-                previousSuggestion = suggestion
-                return
-            }
+        let normalized = normalizeString(text)
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: I think it would be better to move this towards beginning of function. is `text` needed outside of this? Could just set this at beginning and completely remove `let text`?

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 7]
```diff
@@ -88,83 +143,74 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
+        guard suggestion.startsWith(normalized) && normalized.characters.count < suggestion.characters.count else {
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: This is pretty dense to understand esp with the guard and boolean comparisons. I think there is probably a nicer way to move around this guard and one above. Maybe one guard for unwrapping, and a normal `if` for boolean logic?

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 8]
```diff
@@ -88,83 +143,74 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
+            forceResetCursor()
         }
-        removeCompletion()
+    }
+
+    override func caretRect(for position: UITextPosition) -> CGRect {
+        return hideCursor ? CGRect.zero : super.caretRect(for: position)
+    }
+
+    private func createAutocompleteLabelWith(_ autocompleteText: NSAttributedString) -> UILabel {
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: I think a name more like `createLabel(autocompleteText: String)`, or `createAutocompleteLabel(text: String)` are probably a bit nicer.

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 9]
```diff
@@ -192,51 +239,41 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
...
-        if completionActive {
-            // Immediately reuse the previous suggestion if it's still valid.
-            setAutocompleteSuggestion(previousSuggestion)
+    func textDidChange(_ textField: UITextField) {
+        hideCursor = autocompleteTextLabel != nil
+        removeCompletion()
+
+        let isAtEnd = selectedTextRange?.start == endOfDocument
+        let isEmpty = lastReplacement?.isEmpty ?? true
+        if !isEmpty, isAtEnd, markedTextRange == nil {
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: Since these are all booleans, maybe use `&&`? idk, kind of torn on this, maybe we should talk about a convention we want to follow.

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 10]
```diff
@@ -23,37 +23,40 @@ struct AutocompleteTextFieldUX {
...
     // the highlight is active and then the text field is updated accordingly
     // in touchesEnd() (eg. applyCompletion() is called or not)
-    fileprivate var shouldApplyCompletion = false
-    fileprivate var enteredText = ""
-    fileprivate var previousSuggestion = ""
-    fileprivate var notifyTextChanged: (() -> ())? = nil
+    fileprivate var notifyTextChanged: (() -> Void)?
+    private var lastReplacement: String?
+
+    var highlightColor = AutocompleteTextFieldUX.HighlightColor
```
[the remark this answers is not in the document]
Comment (iccub) [reply Client/Frontend/Widgets/AutocompleteTextField.swift]: `Themable` protocol changes it when needed.

File: Client/Frontend/Widgets/AutocompleteTextField.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Widgets/AutocompleteTextField.swift]: They are new(from upstream). They allow to autocomplete url by pressing right or left arrow. Can be deleted if you think we don't need them.

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 11]
```diff
@@ -23,37 +23,40 @@ struct AutocompleteTextFieldUX {
...
-    override var text: String? {
-        didSet {
-            // SELtextDidChange is not called when directly setting the text property, so fire it manually.
-            SELtextDidChange(self)
+    override var accessibilityValue: String? {
+        get {
+            return (self.text ?? "") + (self.autocompleteTextLabel?.text ?? "")
+        }
+        set(value) {
+            super.accessibilityValue = value
```
[the remark this answers is not in the document]
Comment (iccub) [reply Client/Frontend/Widgets/AutocompleteTextField.swift]: I will remove this. We don't utilize accessibility labels anyway, which will change in 2.0.

File: Client/Frontend/Widgets/AutocompleteTextField.swift (hunk 1 above)
Comment (jhreis) [reply Client/Frontend/Widgets/AutocompleteTextField.swift]: No, I like them, just was surprised is all.

File: Client/Frontend/Browser/SearchLoader.swift [hunk 12]
```diff
@@ -123,7 +126,7 @@ class _SearchLoader<UnusedA, UnusedB>: Loader<[Site], SearchViewController> {
             let from = domainWithDotPrefix.index(range.lowerBound, offsetBy: 1)
             let matchedDomain = domainWithDotPrefix.substring(from: from)
             if matchedDomain.contains(".") {
-                return matchedDomain + "/"
+                return matchedDomain
```
Comment (jhreis) [inline Client/Frontend/Browser/SearchLoader.swift]: So we removed the trailing `/` due to 3rd party keyboards? Kind of annoying :/

**Comment by jhreis** [comment]
Release notes can probably be condensed into two items:
- navigation bar improvements
- better 3rd party keyboard support

or something of the nature.

File: Client/Frontend/Browser/SearchLoader.swift (hunk 12 above)
Comment (iccub) [reply Client/Frontend/Browser/SearchLoader.swift]: I wouldn't be too sad about it, all other browsers don't autosuggest addresses with `/` at the end I think
