### PR TITLE
Fix #1432, QR code camera rotation for iPads.

### LINKED ISSUE #1432: iPad Camera isn't upright for scanning QR Code when device is in portrait mode
### Description:
iPad Camera isn't upright for scanning QR Code when device is in portrait mode 

### Steps to Reproduce

  1. Enable Sync on iPad
  2. Scan QR code, enable access to camera
  3. Camera is in wrong orientation. Extremely difficult to point on QR code to scan.

**Actual result:**
image

**Expected result:**
Camera should be in upright position

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6(18.02.05.11)

**Device details:**
iPad (iOS 11)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jhreis @iccub

### PR DESCRIPTION
**Pull request by iccub**
Fixes rotating camera on iPads.

### CODE REVIEW

File: brave/src/frontend/sync/SyncPairCameraViewController.swift [hunk 1]
```diff
@@ -162,6 +164,28 @@ class SyncPairCameraViewController: SyncViewController {
...
         }
     }
+
+    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
+        coordinator.animate(alongsideTransition: nil) { _ in
+            self.cameraView.videoPreviewLayer?.connection.videoOrientation = self.rotateCamera()
+        }
+    }
+
+    private func rotateCamera() -> AVCaptureVideoOrientation {
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncPairCameraViewController.swift]: I think doing something like: https://stackoverflow.com/a/24110800/1429262
would be much cleaner.
