### PR TITLE
Fix #579, open/close dialog on main

### LINKED ISSUE #579: Brave crashes when print cancelled after searching for printers
Description:Brave crashes when print canceled after searching for printers

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should not crash 

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.18 RC1

- Steps to reproduce:
    1. Open any page
    2. Tap on share and select print option
    3. Tap on Search printers, wait till it shows no air printers 
    4. Cancel print, Brave crashes

- Screenshot if needed:

- Any related issues:
#464

### PR DESCRIPTION
**Pull request by jamesmudgett**

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift [hunk 1]
```diff
@@ -918,21 +918,24 @@ class BrowserViewController: UIViewController {
...
-            self.displayedPopoverController = nil
-            self.updateDisplayedPopoverProperties = nil
-
-            if completed {
-                // We don't know what share action the user has chosen so we simply always
-                // update the toolbar and reader mode bar to reflect the latest status.
-                self.updateURLBarDisplayURL(tab)
-                self.updateReaderModeBar()
-            }
+            dispatch_async(dispatch_get_main_queue(), {
```
Comment (garvankeeley) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: Why did you need this, when i checked this was all main thread code?

Did just adding self.helper = nil not fix the problem?
