### PR TITLE
Fix #1419, new sync settings screen UI.

### LINKED ISSUE #1419: Tabs and History not sync'd between devices
### Description:
Tabs and History not sync'd between devices

### Steps to Reproduce

  1. Create a sync group on device 1
  2. Join device 2 to the sync group
  3. Visit couple of sites on device 1 to add browsing history
  4. History doesn't get added to device 2
  5. Tabs visited in device 1 is not created on device 2

**Actual result:**
Tabs and History not sync'd between devices

**Expected result:**
Tabs and history should get added on device 2 when joined to a sync group

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
1.6 (18.01.24.11)

**Device details:**
All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
In addition to the new UI, our own device can't be swiped to delete(need to use button at the bottom).

Text of footer below `Push sync enabled` cell could be improved, I'm not that good at english to make it more descriptive.

img_0258

### CODE REVIEW

**Comment by iccub** [comment]
Added better UX for allowing/denying camera access for qr scanner.
Now after denying access, "Open settings" button is shown that takes user to app settings where he can enable it.

File: brave/src/frontend/sync/SyncCameraView.swift [hunk 1]
```diff
@@ -20,15 +20,51 @@ class SyncCameraView: UIView, AVCaptureMetadataOutputObjectsDelegate {
...
+            openSettingsButton.isHidden = false
+            break
+        default:
+            cameraAccessButton.isHidden = false
+            openSettingsButton.isHidden = true
+            break
+        }
+    }
+
+    var cameraButton: RoundInterfaceButton {
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncCameraView.swift]: This should be a function since it has huge side effects, every time it is accessed it creates a new button.

File: brave/src/frontend/sync/SyncCameraView.swift [hunk 2]
```diff
@@ -20,15 +20,51 @@ class SyncCameraView: UIView, AVCaptureMetadataOutputObjectsDelegate {
         cameraOverlayView.tintColor = UIColor.white
         addSubview(cameraOverlayView)
         
-        cameraAccessButton = RoundInterfaceButton(type: .roundedRect)
+        cameraAccessButton = cameraButton
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncCameraView.swift]: Perform the assignment when defining the button declaration, and make `private let`, do same for `openSettingsButton`

File: brave/src/frontend/sync/SyncSettingsViewController.swift [hunk 3]
```diff
@@ -6,17 +6,15 @@ import Shared
 class SyncSettingsViewController: AppSettingsTableViewController {
     
     private enum SyncSection: Int {
-        
-        case devices, options, reset
+        // Raw values correspond to table sections.
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncSettingsViewController.swift]: ❤️

File: brave/src/frontend/sync/SyncSettingsViewController.swift [hunk 4]
```diff
@@ -50,68 +46,109 @@ class SyncSettingsViewController: AppSettingsTableViewController {
...
+    deinit {
+        NotificationCenter.default.removeObserver(self)
+    }
+
+    override func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
+        return section == SyncSection.pushSync.rawValue ? nil : super.tableView(tableView, viewForHeaderInSection: section)
+    }
+
+    override func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
+        switch section {
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncSettingsViewController.swift]: I think it _may_ be better to do something like:
```
switch SyncSection(fromRaw section)
case .pushSync
case .devices
```

File: brave/src/frontend/sync/SyncSettingsViewController.swift [hunk 5]
```diff
@@ -50,68 +46,109 @@ class SyncSettingsViewController: AppSettingsTableViewController {
...
-        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(SEL_addDevice))
-    }
-    
-    override func viewWillDisappear(_ animated: Bool) {
-        super.viewWillDisappear(animated)
+        devices[indexPath.row].device.remove(save: true)
+
+        // To refresh device list, we need to repopulate all settings sections.
+        settings = []
+        _ = generateSettings()
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncSettingsViewController.swift]: Add `@discardableResult` to `generateSettings` so you can remove the `_ =`

File: brave/src/frontend/sync/SyncCameraView.swift [hunk 6]
```diff
@@ -19,16 +30,44 @@ class SyncCameraView: UIView, AVCaptureMetadataOutputObjectsDelegate {
...
+                make.height.equalTo(40)
+            }
+        }
+
+        switch AVCaptureDevice.authorizationStatus(forMediaType: AVMediaTypeVideo) {
+        case .authorized:
+            cameraAccessButton.isHidden = true
+            openSettingsButton.isHidden = true
+            startCapture()
+            break
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncCameraView.swift]: `break` not needed in Swift

File: brave/src/frontend/sync/SyncSettingsViewController.swift [hunk 7]
```diff
@@ -50,68 +46,111 @@ class SyncSettingsViewController: AppSettingsTableViewController {
...
+        return section == SyncSection.pushSync.rawValue ? nil : super.tableView(tableView, viewForHeaderInSection: section)
+    }
+
+    override func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
+
+        guard let syncSection = SyncSection(rawValue: section) else { return nil }
+
+        switch syncSection {
+        case .pushSync:
+            // TODO: Better/more user friendly text for explaining users what push sync does.
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncSettingsViewController.swift]: This TODO still relevant?

File: Client.xcodeproj/project.pbxproj [hunk 8]
```diff
@@ -3933,6 +3933,7 @@
 					};
 					EB0F42501C9A46D800676650 = {
 						CreatedOnToolsVersion = 7.2;
+						DevelopmentTeam = ULR7CC4V8L;
```
Comment (jhreis) [inline Client.xcodeproj/project.pbxproj]: Remove team

File: brave/src/frontend/sync/SyncSettingsViewController.swift (hunk 7 above)
Comment (iccub) [reply brave/src/frontend/sync/SyncSettingsViewController.swift]: Please look at the attached screenshot(footer text below 'Push sync enabled' cell) and decide if this text is user friendly enough and in correct english. I can remove it then.

Comment (jhreis) [reply brave/src/frontend/sync/SyncSettingsViewController.swift]: Gotcha, we'll leave TODO, and change afterwards if needed.
