### PR TITLE
Fix #1754, QR code scan for sync

### LINKED ISSUE #1754: Sync QR code doesn't work
### Description:

Sync QR code doesn't work 
### Steps to Reproduce

  1. Install 1.6.6
  2. Enable Sync, select enter sync code
  3. Enable camera to scan QR code, doesn't work

**Actual result:**
Sync QR code doesn't work 

**Expected result:**
Should join sync chain with QR code

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy 

**Brave Version:**
1.6.6 (18.10.04.12)

**Device details:**
iPhone 7 (iOS 11.4.1)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
The method signature changed and needs an update.

### CODE REVIEW

File: brave/src/frontend/sync/SyncCameraView.swift [hunk 1]
```diff
@@ -137,10 +137,10 @@ class SyncCameraView: UIView, AVCaptureMetadataOutputObjectsDelegate {
         })
     }
     
-    func captureOutput(_ captureOutput: AVCaptureOutput!, didOutputMetadataObjects metadataObjects: [Any]!, from connection: AVCaptureConnection!) {
+    func metadataOutput(_ output: AVCaptureMetadataOutput, didOutput metadataObjects: [AVMetadataObject], from connection: AVCaptureConnection) {
         
         // Check if the metadataObjects array is not nil and it contains at least one object.
-        if metadataObjects == nil || metadataObjects.count == 0 {
+        if metadataObjects.count == 0 {
```
Comment (jhreis) [inline brave/src/frontend/sync/SyncCameraView.swift]: `if metadataObjects.isEmpty { return }`?
