### PR TITLE
Fix #1297, Don't show password manager button when find in page is tapped.

### LINKED ISSUE #1297: Share icon changes to password manager icon when Search in Page option is selected
### Description:
Share icon changes to key icon when Search in Page option is selected

### Steps to Reproduce
  1. Open any page
  2. Tap on the share icon
  3. Select `Search in page`, share button changes to key, tapping opens up empty share menu

**Actual result:**
[share_menu.zip](https://github.com/brave/browser-ios/files/1450082/share_menu.zip)

**Expected result:**
Share menu icon should not change 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easily reproduced 

**Brave Version:**

1.4.2 (17.09.08.16)

**Device details:**

iPad (iOS 11.1)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
iPad specific, as the search option hides the snackbar on iPhone so literally not possible to check 
@LaurenWags to verify on iPad with iOS 10

### PR DESCRIPTION
**Pull request by iccub**
#### Problem
Code check whether to show password manager button is done when keyboard is shown. So user taps on a form fields and if there are any inputs of password type, the button will show.
Unfortunately, the same thing happens when you choose find in page action, text field becomes first responder, keyboard shows up and the same code logic is performed.

I don't think there is an easy way to distinguish between the two `keyboardWillShow` notifications, so I added a simple flag which is set when find in page action is tapped.
Not the most elegant solution but gets the job done.

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift [hunk 1]
```diff
@@ -1162,8 +1168,15 @@ extension BrowserViewController: KeyboardHelperDelegate {
             if !urlBar.pwdMgrButton.isHidden || loginsHelper.getKeyboardAccessory() != nil {
                 return
             }
-
-                loginsHelper.passwordManagerButtonSetup({ (shouldShow) in
+            
+            // Workaround for #1297. We don't want to check for password manager when find in page action is tapped.
+            // Both use keyboard notification so there is no easy way to distinguish between the two.
+            if showKeyboardFromFindInPage == true {
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: `showKeyboardFromFindInPage` is a non-optional boolean, so no need to check against `== true` since it will explicitly either be true/false itself. (e.g. `true == true` is equivalent to `true`)

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift [hunk 2]
```diff
@@ -99,6 +99,9 @@ class BrowserViewController: UIViewController {
     }
 
     static var instanceAsserter = 0 // Brave: it is easy to get confused as to which fx classes are effectively singletons
+    
+    /// Flag to check if keyboard was triggered by find in page action.
+    var showKeyboardFromFindInPage = false
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: `private`

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift [hunk 3]
```diff
@@ -1000,6 +1003,9 @@ class BrowserViewController: UIViewController {
                 findInPageBar.layoutIfNeeded()
             }
 
+            // Workaround for #1297.
+            // We need to set this flag so `keyboardWillShow` notication won't show password manager button when not needed
+            showKeyboardFromFindInPage = true
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: Can't we just assign the initial value of `showKeyboardFromFindInPage` to `true`, rather than having a default value of `false` and setting it in the `init` here?

Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: Then if you tap on a form field first, like twitter login form, password manager button won't show(keyboard will show and see that `showKeyboardFromFindInPage` is set to true).

App doesn't know what action caused keyboard to show se we need to set this flag either here or when user taps on a form field. I prefer it here as find in page is used less than tapping on login forms.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: will go with `fileprivate` cos its used in an extension

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift (hunk 3 above)
Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController.swift]: Oohh, Github was cropping the code funny, and it looked like this was part of the `init` function. Should have looked at line numbers/function.
