### PR TITLE
fix #903, fix 916 - tab loss issues, make preservation more efficient…

### LINKED ISSUE #903: Tabs lost after re-launching the app
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Tabs lost after re-launching the app

**Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6(iOS 10.3.3)
iPhone 7+(iOS 10.3.3)

**Brave Version:**
1.4(17.06.12.13)

**Steps to reproduce:**
    1. Browser for a while with lots of tabs open
    2. Double tap home button and kill the app
    3. Wait for a while before relaunching the app, all tabs are lost upon restart

**Actual Behavior**
All tabs are lost when app is killed and launched after a while 

**Expected Behavior**
Should retain all tabs irrespective of when the app is opened after closing it

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
Not that I have experienced, but it is as per https://github.com/brave/browser-ios/issues/788#issuecomment-307659178

**Can this issue be consistently reproduced?**
Yes on the beta build

**Extra QA steps:**
    1. 
    2. 
    3.

** Website problems only:** N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? N/A

**Screenshot if needed:**

**Any related issues:**
#788

### PR DESCRIPTION
**Pull request by jamesmudgett**
… by only worrying about archiving data from loaded tab. removed overused preservetabs calls

### CODE REVIEW

File: Client/Frontend/Browser/TabManager.swift [hunk 1]
```diff
@@ -480,10 +469,10 @@ extension TabManager : WKCompatNavigationDelegate {
         // only store changes if this is not an error page
         // as we current handle tab restore as error page redirects then this ensures that we don't
         // call storeChanges unnecessarily on startup
-        if let url = tabForWebView(webView)?.url {
+        if let tab = tabForWebView(webView), let url = tabForWebView(webView)?.url {
             if !ErrorPageHelper.isErrorPageURL(url) {
                 postAsyncToMain(0.25) {
-                    self.preserveTabs()
+                    TabMO.preserveTab(tab, tabManager: self)
```
Comment (jhreis) [inline Client/Frontend/Browser/TabManager.swift]: Why change to a class method, when still just passing in self?

File: Client/Frontend/Browser/TabManager.swift [hunk 2]
```diff
@@ -241,8 +234,6 @@ class TabManager : NSObject {
         for delegate in delegates {
             delegate.value?.tabManagerDidAddTabs(self)
         }
-
-        preserveTabs()
```
Comment (jhreis) [inline Client/Frontend/Browser/TabManager.swift]: These `preserveTabs` removals are not necessary at all?

Comment (jamesmudgett) [inline Client/Frontend/Browser/TabManager.swift]: The way this worked before is anytime something changed state (remove tab, start new one, page loaded) the entire open tab data would be reanalyzed then saved into core data. In other words, tabs that had no changes would be rewritten. The problem with this is that it would occasionally fail on some of the other tabs since switching between private and public would cause the non private tab sessions to be archived into localhost urls in web view and any history data would really be inaccessible when running into memory problems and would be updating core data with these incomplete data.

Comment (jamesmudgett) [inline Client/Frontend/Browser/TabManager.swift]: The way it's working now a single TabMO is responsible for preserving of only its data. We no longer iterate over all tabs.

File: Client/Frontend/Browser/TabManager.swift (hunk 1 above)
Comment (jamesmudgett) [inline Client/Frontend/Browser/TabManager.swift]: @jhreis class method is now on TabMO has no scope for TabManager

File: Client/Frontend/Browser/TabManager.swift (hunk 2 above)
Comment (jhreis) [inline Client/Frontend/Browser/TabManager.swift]: Ah, sounds good, thanks for the explanation. Was just assuming `preserveTab` was moved, I see the modifications now.
