### PR TITLE
fix #1602 - re-evaluate favicon by removing from cache

### LINKED ISSUE #1602: fuzzy favicon displayed on Favorite tile if site is bookmarked first
### Description:
Originally reported in https://github.com/brave/browser-ios/issues/1551#issuecomment-389625695 - if you bookmark a site with a small icon (quora.com, kpwags.com, etc) and then add the site to Favorites (formerly top site tiles), the favicon will be fuzzy. It should be a single letter on a solid background as described in #1551.

### Steps to Reproduce

  1. Navigate to a site like quora.com
  2. Bookmark the site.
  3. Now go to the share menu and add the site to favorites.
  4. Open a new tab.

**Actual result:**
Quora favicon is fuzzy.
img_0184

**Expected result:**
It should be a single letter on a solid background like the K in the screenshot above.

**Reproduces how often:** [Easily reproduced/Intermittent issue]
easily

**Brave Version:**

1.6 (18.05.16.13)

**Device details:**

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
If you add to favorites, and then bookmark the site, you get the single letter on a solid background as the favicon.

cc @jamesmudgett @jhreis

### PR DESCRIPTION
**Pull request by jamesmudgett**

### CODE REVIEW

File: Client/Frontend/Browser/Browser.swift [hunk 1]
```diff
@@ -105,7 +105,15 @@ class Browser: NSObject, BrowserWebViewDelegate {
     var pendingScreenshot = false
     
     // Tab color
-    var color: UIColor?
+    var color: UIColor? {
+        didSet {
+            guard let url = url else { return }
+            let context = DataController.shared.workerContext
+            debugPrint((color ?? FallbackIcon.color).toHexString())
```
Comment (jhreis) [inline Client/Frontend/Browser/Browser.swift]: Use XCLogger.
