### PR TITLE
Fix #1080 and #1077

### LINKED ISSUE #1080: Google Keyboard searching issue
- Did you search for similar issues before submitting this one?
Yes

- Description:
Google Keyboard don't recognise autocomplete URL, instead searched for entered text.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.4.1

- Steps to reproduce:
    1. Install Google Keyboard
    2. Enter text like "goo", which results in prediction like "google.com"
    3. Press Go/Enter

- Actual Behavior
Search on google for "goo"

- Expected Behavior
Go to google.com

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by kunalverma25**

### CODE REVIEW

File: brave/src/frontend/BraveScrollController.swift [hunk 1]
```diff
@@ -207,9 +209,15 @@ class BraveScrollController: NSObject {
         defer {
             entrantGuard = false
         }
+        
+        print(change, context, object)
```
Comment (jhreis) [inline brave/src/frontend/BraveScrollController.swift]: Please remove logging

File: brave/src/frontend/BraveScrollController.swift [hunk 2]
```diff
@@ -207,9 +209,15 @@ class BraveScrollController: NSObject {
...
+        print((object as? UIScrollView)?.superview?.isFirstResponder)
+        
         if (keyPath ?? "") == "contentSize" { // && browser?.webView?.scrollView === object {
             browser?.webView?.contentSizeChangeDetected()
-            checkHeightOfPageAndAdjustWebViewInsets()
+            postAsyncToMain(0.2) {
```
Comment (jhreis) [inline brave/src/frontend/BraveScrollController.swift]: What is the reason for the delay? Does it just need to be scheduled for the end of the runloop?

File: Client.xcodeproj/project.pbxproj [hunk 3]
```diff
@@ -4770,7 +4772,7 @@
 				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
 				CODE_SIGN_ENTITLEMENTS = brave/Brave.entitlements;
 				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
-				DEVELOPMENT_TEAM = "";
+				DEVELOPMENT_TEAM = B75YN3KWEL;
```
Comment (jhreis) [inline Client.xcodeproj/project.pbxproj]: Please remove personal dev team

File: Cartfile [hunk 4]
```diff
@@ -5,7 +5,7 @@ github "kif-framework/KIF"          "v3.5.1"
 github "mozilla/readability"        "master"
 github "rs/SDWebImage"              "3.8.2"
 github "SnapKit/SnapKit"            "3.0.0"
-github "jrendel/SwiftKeychainWrapper"       "3.0.1"
+github "jrendel/SwiftKeychainWrapper"       "3.0"
```
Comment (jhreis) [inline Cartfile]: This change required for the related issues?

File: brave/src/frontend/BraveScrollController.swift [hunk 5]
```diff
@@ -143,7 +143,7 @@ class BraveScrollController: NSObject {
     }
     
     // This causes issue #216 if contentInset changed during a load
-    func checkHeightOfPageAndAdjustWebViewInsets() {
+    func checkHeightOfPageAndAdjustWebViewInsets(_ overlay: Bool = false) {
```
Comment (jhreis) [inline brave/src/frontend/BraveScrollController.swift]: When calling this function, the reason for the `Bool` is not inferred by the named parameters. Please include a descriptive named parameter that also aligns with a `Bool` type (e.g. `hasOverlay`)

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 6]
```diff
@@ -134,11 +134,15 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
 
         if completionActive {
             if string.isEmpty {
-                // Characters are being deleted, so clear the autocompletion, but don't change the text.
-                removeCompletion()
-                return false
+                if range.length > 0 {
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: Just add combine these if statements, and remove the `else`:

```
if string.isEmpty && range.length > 0 {
    // ...
    return false
}
// ...
```

**Comment by jhreis** [comment]
Really appreciate the PR! Just a few changes, and I'll pull it down and take a closer look.

**Comment by kunalverma25** [comment]
@jhreis 
I've made the changes, please have a look.
Thanks..

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 7]
```diff
@@ -133,10 +133,10 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
         canAutocomplete = !string.isEmpty
 
         if completionActive {
-            if string.isEmpty {
-                // Characters are being deleted, so clear the autocompletion, but don't change the text.
-                removeCompletion()
-                return false
+            if string.isEmpty && range.length > 0 {
+                    // Characters are being deleted, so clear the autocompletion, but don't change the text.
```
Comment (jhreis) [inline Client/Frontend/Widgets/AutocompleteTextField.swift]: Remove added indentation.

File: README.md [hunk 8]
```diff
@@ -25,7 +25,7 @@ brew install carthage
 
 <strong> 5. Download the source code: </strong>
 ```
-git clone https://github.com/brave/browser.git # this will download git if it isn't currently installed
+git clone https://github.com/brave/browser-ios.git # this will download git if it isn't currently installed
```
Comment (jhreis) [inline README.md]: Nice catch.

File: brave/src/frontend/BraveScrollController.swift [hunk 9]
```diff
@@ -143,7 +143,7 @@ class BraveScrollController: NSObject {
     }
     
     // This causes issue #216 if contentInset changed during a load
-    func checkHeightOfPageAndAdjustWebViewInsets() {
+    func checkHeightOfPageAndAdjustWebViewInsets(_ didKeyboardAppear: Bool = false) {
```
Comment (jhreis) [inline brave/src/frontend/BraveScrollController.swift]: Keep named parameter, they are there to define what is being passed in, and it isn't inferred by the method name, for example it is hard to know what the difference between:
`adjustWebViewInsets(true)` and `adjustWebViewInsets(false)` is without looking at the method declaration.

Keeping the param name allows a reader to identify immediately what the Bool represents (e.g. `adjustWebViewInsets(keyboardAppeared: true)`, I know what `true` represents now.

**Comment by kunalverma25** [comment]
@jamesmudgett 
Fixed the typo.
Please have a look. Thanks.

**Comment by kunalverma25** [comment]
@jamesmudgett @jhreis 
Can you review the pull request with the changes and then merge if looks good?

**Comment by jamesmudgett** [comment]
Great work!
