### PR TITLE
Fix #1136: On launching via a scheme (e.g. Open in Brave, 3d touch), …

### LINKED ISSUE #1136: crash when selecting "New Tab" via 3D touch on Brave icon
**- Did you search for similar issues before submitting this one?**
Yes

**- Description:**
When selecting the "New Tab" option under the Brave icon via 3D touch, the browser will open and instantly crash.

**- Device (iPhone5, iPhone6s plus, iPad 3, ?):**
iPhone 6s+ running iOS 10.3.3 - Reproduced (Requires 3D touch)

**- Brave Version:**
v1.4.1 (17.08.25.08) - Reproduced (current release)
v.1.4.1 (17.08.28.10) - Reproduced (lastest master ec94ec0958fa650dca59c78b662f7bf86c0ba9d5)

**- Steps to reproduce:**

1. Tap on the Brave icon using 3D touch and select "New Tab"

**- Actual Behavior**
Brave is opened and instantly crashes

**- Expected Behavior**
Brave should launch and open a new tab without crashing

**- Is this an issue with Beta build?**
Yes

**- Is this an issue in the currently released version?**
Yes

**- Can this issue be consistently reproduced?**
Yes, 100% reproducible using the above STR

**- Screenshot if needed:**
Attached Stack of crash: [Crash Stack](https://github.com/brave/browser-ios/files/1258385/btStack.txt)

### PR DESCRIPTION
**Pull request by jhreis**
…the current tab index was nil leading to an outofbounds exception and crash.

### CODE REVIEW

File: Client/Frontend/Browser/TabManager.swift [hunk 1]
```diff
@@ -396,18 +401,13 @@ class TabManager : NSObject {
 
         let isPrivate = PrivateBrowsing.singleton.isOn
         let tab = Browser(configuration: self.configuration, isPrivate: isPrivate)
-        if id == nil {
-            tab.tabID = TabMO.freshTab()
-        }
-        else {
-            tab.tabID = id
-        }
+        tab.tabID = id ?? TabMO.freshTab()
```
Comment (jamesmudgett) [inline Client/Frontend/Browser/TabManager.swift]: great cleanup
