### PR TITLE
fix #1160 - crash on pb mode only, filestyem locked, crash found when…

### LINKED ISSUE #1160: Beta build crashes when navigating to settings
- Did you search for similar issues before submitting this one?
Yes

- Description:
Beta build crashes when navigating to settings

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3.)
- Brave Version:
1.4.3(17.09.11.16)
- Steps to reproduce:
    1. Install older beta build 1.4.2( 17.09.11.15) via crahalytics
    2. Set private only browsing mode 
    3. Upgrade to the latest beta 1.4.3. 
    4. Open browser and tap on left menu
    5. Tap on the settings icon, browser crashes

- Actual Behavior
Browser crashes when loading settings

- Expected Behavior
Should not crash
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. Clean installing of 1.4.3(17.09.11.16) doesn't cause crash 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by jamesmudgett**
… trying to access image cache

### CODE REVIEW

File: brave/src/webview/PrivateBrowsing.swift [hunk 1]
```diff
@@ -123,7 +123,7 @@ class PrivateBrowsing {
         //  if it is overwritten, it will lead to race conditions, and generally a dropped deferment, since the
         //  notification will be executed on _only_ the newest version of this property
         exitDeferred = Deferred<Void>()
-        isOn = false
```
Comment (jamesmudgett) [inline brave/src/webview/PrivateBrowsing.swift]: Placement here could have likely caused other unexpected behavior when checking isOn from tabmanager or elsewhere while removing private tabs. Should be set just before notification, moved below.
